### ISSUE TITLE
any advice to improve the result?  

### ISSUE THREAD

**Issue by ersanliqiao** [seungjun45/Shading-Removal#1]

**Comment by seungjun45** [comment]
Hi!

Thank you for your interest. :D
Well, I think there are two approaches to greatly improve the "water-filling" algorithm.

First, the algorithm is weak for spotlighted (strong light intensity) regions. it will be great if you can handle this problem (the algorithm will become more perfect).

Second, in the paper, I set the drainage points to be the image boundary. This constraint is very powerful for camera-captured document images only. However, if you find a better solution to detect shadows (and set their local minima to be the drainage point), I think the algorithm can be applied to all (possibly) types of images.

**Comment by ersanliqiao** [comment]
Thank you for your advice，I will take more time to understand your opinion. Now I have found that it's not good to process hard shadow image. Have you ever try to improve the two steps including flood-effuse and incremetal-filling?

**Comment by ersanliqiao** [comment]
> Hi!
> 
> Thank you for your interest. :D
> Well, I think there are two approaches to greatly improve the "water-filling" algorithm.
> 
> First, the algorithm is weak for spotlighted (strong light intensity) regions. it will be great if you can handle this problem (the algorithm will become more perfect).
> 
> Second, in the paper, I set the drainage points to be the image boundary. This constraint is very powerful for camera-captured document images only. However, if you find a better solution to detect shadows (and set their local minima to be the drainage point), I think the algorithm can be applied to all (possibly) types of images.


"I set the drainage points to be the image boundary."  Does this sentence mean that it's bad to process shadows which is not adjacent to image boundary? But I have not understand where does your code do any special processing for this, because your code is processing image pixel by pixel. I think you have not do any specail processing for pixels adjacent to  image boundary.

**Comment by seungjun45** [comment]
> Thank you for your advice，I will take more time to understand your opinion. Now I have found that it's not good to process hard shadow image. Have you ever try to improve the two steps including flood-effuse and incremetal-filling?

Not really :)
I wanted to submit the paper with the simplest algorithm so that it can be improved so far.
I would encourage you to give a try.

**Comment by seungjun45** [comment]
> > Hi!
> > Thank you for your interest. :D
> > Well, I think there are two approaches to greatly improve the "water-filling" algorithm.
> > First, the algorithm is weak for spotlighted (strong light intensity) regions. it will be great if you can handle this problem (the algorithm will become more perfect).
> > Second, in the paper, I set the drainage points to be the image boundary. This constraint is very powerful for camera-captured document images only. However, if you find a better solution to detect shadows (and set their local minima to be the drainage point), I think the algorithm can be applied to all (possibly) types of images.
> 
> "I set the drainage points to be the image boundary." Does this sentence mean that it's bad to process shadows which is not adjacent to image boundary? But I have not understand where does your code do any special processing for this, because your code is processing image pixel by pixel. I think you have not do any specail processing for pixels adjacent to image boundary.

In the code, the image boundary regions are not included in for-loops. Then, the water level at the image boundary will be constantly set to 0. This is how I set the drainage points to be the image boundary (think about water falling at the waterfall).

**Comment by ersanliqiao** [comment]
OK, thank you very much!!
