### ISSUE TITLE
A Python Implementation

### ISSUE THREAD

**Issue by WhaSukGO** [seungjun45/Shading-Removal#3]
(Although it's an old repository, I hope I can reach you by any chance)

First of all, thank you for sharing such an amazing work.

I'm trying to implement in [Python](https://github.com/WhaSukGO/Water-Filling-Python/blob/main/main.py), but I couldn't get it right.

I believe I used the same OpenCV function, but the result is the same as the original image.

Any help is appreciated!

**Comment by WhaSukGO** [comment]
Found a bug. Now working fine! 

Thank you for your work again!

**Comment by Abhiprit-P** [comment]
How to keep the background color of input and output images same?
